### ISSUE TITLE
For some PDFs plainAddPlaceholder returns error, although it works for w3dummy.pdf

### ISSUE THREAD

**Issue by vologab** [vbuch/node-signpdf#50] opened 2019-12-25 08:11 UTC
```javascript
function signExistingPDF(pdfFile: string) {
  let pdfBuffer = readFileSync(pdfFile);
  pdfBuffer = plainAddPlaceholder({
      pdfBuffer,
      reason: 'I have reviewed it.',
      // signatureLength: 1612,
  });

  return pdfBuffer;
}
```

Stack trace
```text
TypeError: Cannot read property 'split' of undefined
    at getXref (/.../node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:55:34)
    at getFullXrefTable (/.../node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:79:25)
    at readRefTable (/.../node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readRefTable.js:100:25)
    at readPdf (/.../node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/readPdf.js:31:46)
    at plainAddPlaceholder (/.../node_modules/node-signpdf/dist/helpers/plainAddPlaceholder/index.js:54:37)
    at signExistingPDF (/.../pdfsig/index.ts:66:15)
........
```

Although it works for w3dummy.pdf

**Comment by sumanmaity1234** [comment] 2019-12-26 06:18
I am using this module to sign an existing PDF. In my case, I am not getting any errors on console but when I am trying to open the PDF on **Acrobat Adobe Reader** I am getting the following issue

<img width="698" alt="Screenshot 2019-12-26 11 41 07" src="https://user-images.githubusercontent.com/48752670/71461131-b61b1680-27d4-11ea-8b27-f84bf9150874.png">
also the first page of PDF is becomig empty page.

I am attaching both (signed and unsigned) PDFs for reference
[hackerNews.pdf](https://github.com/vbuch/node-signpdf/files/4001560/hackerNews.pdf)
[hackerNews-sign.pdf](https://github.com/vbuch/node-signpdf/files/4001559/hackerNews-sign.pdf)

**Comment by lucasmassi** [comment] 2020-01-15 14:06
@sumanmaity1234 add your comment to my issue #55 this problem happens to me too

**Comment by vbuch** [comment] 2020-01-30 18:50
@sumanmaity1234 with the changes from #57 I ran signing on the attached hackerNews.pdf. Here is the outcome: [hackerNews-signed.pdf](https://github.com/vbuch/node-signpdf/files/4135763/hackerNews-signed.pdf) Could you confirm for me that this fixes this issue?

@vologab any chance this also fixes the initial issue?

**Comment by vbuch** [comment] 2020-01-30 22:25
@vologab @sumanmaity1234 @lucasmassi #57 is now in 1.2.2. Could you check if your issues are still reproducible or this one can be closed?

**Comment by sumanmaity1234** [comment] 2020-01-31 08:35
Hi @vbuch, looks like the issue has been resolved with the latest changes. Thanks for fixing it.

I think this issue can be marked as fixed until @vologab @lucasmassi has some other points.

**Closed** 2020-01-31 09:03 UTC
