### ISSUE TITLE
How to use it in Vue project,dont support spread (...)

### ISSUE THREAD

**Issue by jackeyWanFei** [vbuch/node-signpdf#37] opened 2019-10-24 02:04 UTC
![image](https://user-images.githubusercontent.com/20556765/67447148-88cfb200-f645-11e9-9991-4d9ac4f98258.png)

**Comment by vbuch** [comment] 2019-10-24 07:46
You probably had that issue with other projects as well. You need to rebuild it. That means that you would need the appropriate babel config that will make a dist that can work for you. If you manage, please make a PR. Would love to have it working for more projects.

**Comment by jackeyWanFei** [comment] 2019-10-31 08:01
> You probably had that issue with other projects as well. You need to rebuild it. That means that you would need the appropriate babel config that will make a dist that can work for you. If you manage, please make a PR. Would love to have it working for more projects.

thanks, another question, did it support signature stamper ?

**Comment by vbuch** [comment] 2019-10-31 08:40
Not sure what that signature stamper is

**Comment by jackeyWanFei** [comment] 2019-10-31 09:08
> Not sure what that signature stamper is so probably not

Sorry about it, in itext, call it stamper,  it's mean sign with a picture.
![image](https://user-images.githubusercontent.com/20556765/67933383-a4682900-fc00-11e9-9ff2-8b43fbcea3d2.png)
Like the red stamper in this picture

Sorry about my poor English.。

**Comment by jackeyWanFei** [comment] 2019-10-31 09:10
When open it by Adobe Acrobat, and click the red stamper, will show the signature info.

**Comment by vbuch** [comment] 2019-10-31 11:08
The library only takes care of digitally signing. I was planning a helper or test that demonstrates how the visual part can be implemented but dont have the time for that. You need to do the drawing yourself and then force the clickability through applying the signature with the lib.

**Comment by jackeyWanFei** [comment] 2019-10-31 12:40
OK, Thanks a lot, I'll try it myself.  It's important in my project. I was stoped here for three weeks.
I found another library as "https://github.com/Communication-Systems-Group/pdfsign.js". And I found your answer in the Issues. Hahahaha

**Comment by vbuch** [comment] 2019-10-31 14:58
node-signpdf was initially based on the work done in pdfsign.js, so...yes... related.
Basically you need to find a way to draw the red thing on the page. Once you have that, you will ned to put the clickable widget on top of it. It is as simple as that: https://github.com/vbuch/node-signpdf/pull/38/files/04386891fb3ba8f34d1c71419021ae31f7ab820a#diff-6fe2c52077723f3fcbc54f7763b81bd6

@maldimirov can you easily pase some code that draws something simple on a page and applies the signature on top? Some random blob would be fine.

**Comment by therpobinski** [comment] 2019-11-07 20:15
Hi guys, this issue fits me perfectly. I am looking for how to make a widget in the signature. I'm checking the code a bit and I see that if I use the `./src/helpers/plainAddPlaceholder/index.js`, which is for files that are already created, I see that it occupies the file `./src/helpers/pdfkitAddPlaceholder.js` to get the form and the widget and with this function `createBufferPageWithAnnotation` adds the witget, That is what I understand for now before testing. I would like to know if there is how to put this widget to each page of the pdf?
And if you interpret the code well?

**Comment by vbuch** [comment] 2019-11-11 11:51
@jackeyWanFei , you might be interested in [pdf-lib here](https://github.com/Hopding/pdf-lib). It follows an API similar to the one of foliojs/pdfkit but also allows editing. So you could probably add the graphic and the placeholder with it and just apply the signature. You could share your experiments if you do that, because I am planning to add that as helpers here next to the pdfkit and plain helpers. Would be nice to see it work for someone.

**Comment by vbuch** [comment] 2019-11-11 22:44
While the original topic was very specific, the author asked another, totally unrelated question and the issue is now a bad quality one. Closing. I'm sure whoever needs more info will find their way to it.

**Closed by vbuch** 2019-11-11 22:44 UTC
