### ISSUE TITLE
I have made invisible signature with node-signpdf lib, but i can't make it display the signature on Acrobat reader (visible signature). How can i display my signature that is visible?

### ISSUE THREAD

**Issue by mayank23jne** [vbuch/node-signpdf#143] opened 2021-07-23 08:47 UTC
I have made invisible signature with node-signpdf lib, but i can't make it display the signature on Acrobat reader (visible signature). How can i display my signature that is visible?

**Comment by vbuch** [comment] 2021-08-30 10:37
Closing this one as it is a duplicate of #129

**Closed by vbuch** 2021-08-30 10:37 UTC
