### ISSUE TITLE
Unable to save a valid version of the signed PDF file

### ISSUE THREAD

**Issue by radoslavpetranov** [vbuch/node-signpdf#58] opened 2020-02-03 18:31 UTC
**Describe the bug and the expected behaviour**
Here is a test function that I use to test signing a dummy PDF document with a dummy certificate.

```
export const testFileSigning = (_req: Request, res: Response, next: NextFunction) => {

  // Hardcode some paths for testing purposes
  const pdfFilePath = "c:/temp/cert/cert.pdf";
  const pdfSignedFilePath = "c:/temp/cert/cert_signed.pdf";
  const certFilePath = "c:/temp/cert/certificate.p12";

  // Create some streams
  const p12Buffer = fs.readFileSync(certFilePath);
  let pdfBuffer = fs.readFileSync(pdfFilePath);

  // Add placeholder
  pdfBuffer = plainAddPlaceholder.default({
    pdfBuffer,
    reason: 'I have reviewed it.',
    signatureLength: 8192,
  });
  try {
    // Sign the doc
    pdfBuffer = signer.sign(pdfBuffer, p12Buffer);
  } catch (err) {
    console.error(`Error signing document`, err);
    next(err);
  }

  // Write to file
  fs.writeFile(pdfSignedFilePath, pdfBuffer, { encoding: 'binary' }, (err) => {
    if (!!err) {
      next(err);
    } else {
      res.locals.data = { signed: true };
      next();
    }
  });
};
```
So `fs.writeFile` saves the `pdfBuffer` that results from the `sign` method into a file called `cert_signed.pdf`.

When I open the file, the file is blank, it's broken / tiny so that it's zoomed in to like 4000% 

![image](https://user-images.githubusercontent.com/2715732/73678816-768bf800-46b9-11ea-9b47-15263a5272b1.png)

and when I try to zoom out I see that error

`There was a problem reading this document (14)`

![image](https://user-images.githubusercontent.com/2715732/73678838-8277ba00-46b9-11ea-82ed-1c94f97335aa.png)

and the file itself seems to be corrupt / empty.

**Is it a bug in signing or in the helpers?**
I am not even sure if this is a bug or if I'm doing something wrong when trying to save the signed file. If it's a bug I would assume it's a bug with the `sign` function.

**To Reproduce**
I've described how to reproduce the issue in the previous points. I am testing with the `certificate.p12` file that comes in this repo. I have also attached the 2 PDF files: the source `cert.pdf` file as well as the resulting `cert_signed.pdf` file.

[cert.pdf](https://github.com/vbuch/node-signpdf/files/4149392/cert.pdf)
[cert_signed.pdf](https://github.com/vbuch/node-signpdf/files/4149423/cert_signed.pdf)

Your help would be appreciated. [I saw someone else pointing to this error in a closed github issue](https://github.com/vbuch/node-signpdf/issues/50#issuecomment-568983452) so I figured I would make a separate issue for anyone facing the same problem as me.

**Comment by radoslavpetranov** [comment] 2020-02-03 18:39
Interestingly enough, here's what the `cert_signed.pdf` file looks like in chrome

![2020-02-03_19h38_38](https://user-images.githubusercontent.com/2715732/73680652-ec459300-46bc-11ea-873e-4ae5206d9d81.png)

and here what it looks like in Adobe Acrobat Reader DC

![image](https://user-images.githubusercontent.com/2715732/73680609-d932c300-46bc-11ea-8b5c-f0b219a11fbc.png)

**Comment by vbuch** [comment] 2020-02-04 09:03
In the resulting PDF I see ```2 0 obj
<<

/Type /Catalog
/Pages 1 0 R

/AcroForm 17 0 R
>>
endobj

6 0 obj
<<
 16 0 R]
/Contents 4 0 R
/Resources 5 0 R


>>
endobj
```

This looks wrong. Not sure what got broken there without going through code. What version are you using? Is it 1.2.2?

**Comment by radoslavpetranov** [comment] 2020-02-04 09:11
Thanks for looking into this! Yes, I am using version `1.2.2`.

Here's the updated code that saves the file after adding the placeholder

```
// Hardcode some paths for testing purposes
  const pdfFilePath = "c:/temp/cert/cert.pdf";
  const pdfWithPlaceholderFilePath = "c:/temp/cert/cert_placeholder.pdf";

  //let readableStream = generateNewPdfDocumentWithCertificatePlaceholder("This is test content.\nThis is test content.");
  // Create some streams
  let pdfBuffer = fs.readFileSync(pdfFilePath);

  // Add placeholder
  pdfBuffer = plainAddPlaceholder.default({
    pdfBuffer,
    reason: 'I have reviewed it.',
    signatureLength: 8192,
  });
  fs.writeFile(pdfWithPlaceholderFilePath, pdfBuffer, { encoding: 'binary' }, (err) => {
    if (!!err) {
      next(err);
    } else {
      res.locals.data = { signed: true };
      next();
    }
  });
```

And the resulting file is attached.

[cert_placeholder.pdf](https://github.com/vbuch/node-signpdf/files/4152334/cert_placeholder.pdf)

**Comment by vbuch** [comment] 2020-02-04 09:29
OK. Confirmed. It's an issue with `plainAddPlaceholder`. The page object gets broken through it.

**Comment by radoslavpetranov** [comment] 2020-02-04 11:01
I'm no PDF expert but I'll see if I can figure out what's going on.

I just used a hex editor and I confirm that if I change the broken `obj` part from

```
6 0 obj
<<
 16 0 R]
/Contents 4 0 R
/Resources 5 0 R


>>
endobj
```

to

```
6 0 obj
<<
/Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.28 841.89]
/Contents 4 0 R
/Resources 5 0 R
>>
endobj
```

the file gets properly rendered

![image](https://user-images.githubusercontent.com/2715732/73739067-ddef8980-4745-11ea-8d66-e9142bf86854.png)

**Comment by vbuch** [comment] 2020-02-04 12:47
And this resulting one you will be able to sign. The problem is somewhere in plainaddplaceholder. Somewhere where this `/type /page` object is written back in the pdf. Probably around here: https://github.com/vbuch/node-signpdf/blob/develop/src/helpers/plainAddPlaceholder/createBufferPageWithAnnotation.js

**Comment by vbuch** [comment] 2020-02-06 09:11
@radoslavpetranov (now that I wrote your name I am pretty sure you are also a Bulgarian :-))
Can try and check the code in #59 I will get this to 1.2.3 later today but if you could confirm meanwhile, would be really nice. Thanks.

**Comment by radoslavpetranov** [comment] 2020-02-06 11:27
Guilty as charged :)

I just tested your changes and everything works great now! Thanks a lot for figuring this out!!

![image](https://user-images.githubusercontent.com/2715732/73933071-fc878900-48db-11ea-81f1-6230920a52bb.png)

**Comment by vbuch** [comment] 2020-02-06 20:08
Have not released yet. Just merged into develop.

**Comment by vbuch** [comment] 2020-02-06 20:25
1.2.3 is out in npm. Hope it fixes this issue.

**Closed** 2020-02-06 20:27 UTC
Labels: bug
